[project]
name = "image-to-svg"
version = "0.1.0"
description = "Convert an image into SVG format"
readme = "README.md"
authors = [
    { name = "Baptiste Gregorutti", email = "" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "tqdm>=4.67.3",
]

[project.scripts]
image-to-svg = "image_to_svg.converter:cli"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
